# Generated by Django 5.0.6 on 2024-05-19 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("priority", models.IntegerField()),
                ("color", models.CharField(max_length=7)),
                ("background_color", models.CharField(max_length=7)),
                ("active", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.IntegerField()),
                ("style", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=255)),
                ("relative_url", models.CharField(max_length=255)),
                ("image", models.URLField(max_length=500)),
                ("delivery", models.CharField(max_length=50)),
                ("online", models.BooleanField()),
                ("active", models.BooleanField()),
                ("is_customizable", models.BooleanField()),
                ("paid_print", models.BooleanField()),
                ("is_exclusive", models.BooleanField()),
                (
                    "customization_template_id",
                    models.IntegerField(blank=True, null=True),
                ),
                ("currency", models.CharField(max_length=10)),
                ("url", models.URLField(max_length=500)),
                ("attributes", models.JSONField()),
                (
                    "labels",
                    models.ManyToManyField(
                        related_name="products", to="products.label"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku_id", models.IntegerField()),
                ("size_id", models.IntegerField()),
                ("barcode", models.CharField(max_length=20)),
                ("order_by", models.IntegerField()),
                ("name", models.CharField(max_length=50)),
                ("name_short", models.CharField(max_length=50)),
                ("stock_info", models.CharField(blank=True, max_length=255, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "recommended_retail_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("supplier", models.CharField(max_length=50)),
                ("is_marketplace", models.BooleanField()),
                ("availability", models.CharField(max_length=50)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
